SYNPY-1137 migration fixes
Sage-Bionetworks/synapsePythonClient pull request #848
Opened 2021-04-12 18:18 UTC by jkiang13

Addresses the following issues, one per commit:

[SYNPY-1123](https://sagebionetworks.jira.com/browse/SYNPY-1123)
[SYNPY-1130](https://sagebionetworks.jira.com/browse/SYNPY-1130) 
[SYNPY-1134](https://sagebionetworks.jira.com/browse/SYNPY-1134)
[SYNPY-1135](https://sagebionetworks.jira.com/browse/SYNPY-1135)
[SYNPY-1136](https://sagebionetworks.jira.com/browse/SYNPY-1136)

2021-04-13 00:01 UTC, zimingd requested changes

2021-04-13 22:22 UTC, pep8speaks commented
Hello @jkiang13! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:











* In the file [`tests/unit/synapseutils/unit_test_synapseutils_migrate.py`](https://github.com/Sage-Bionetworks/synapsePythonClient/blob/61df839d687d8b09fa28caa4e4cbbd714c6b112b/tests/unit/synapseutils/unit_test_synapseutils_migrate.py):

> [Line 2014:8](https://github.com/Sage-Bionetworks/synapsePythonClient/blob/61df839d687d8b09fa28caa4e4cbbd714c6b112b/tests/unit/synapseutils/unit_test_synapseutils_migrate.py#L2014): [E121](https://duckduckgo.com/?q=pep8%20E121) continuation line under-indented for hanging indent

2021-04-13 22:23 UTC, jkiang13 commented on tests/unit/synapseutils/unit_test_synapseutils_migrate.py
> +        {'fileHandle': file_handle} for file_handle in file_handles
The structure of the mocked file handles was wrong with the extra key as you noted. This test was testing a private function. It asserts that the file handle returned from _getFileHandleDownload is passed through in tact which it was but the mocked structure was wrong. Fixed the structure of the mock to be consistent with reality.

2021-04-14 03:57 UTC, zimingd approved these changes

2021-04-14 03:58 UTC, merged