Synpy 1146 writing boolean from df into synapse table
Sage-Bionetworks/synapsePythonClient pull request #862
Opened 2021-05-19 18:17 UTC by linchiahuisage

Change

- fix the issue that pandas infer the data type of coulmn
- add unit test to verify column type are match with Synapse table

2021-05-20 14:48 UTC, jkiang13 requested changes

2021-05-20 14:48 UTC, jkiang13 commented on synapseclient/table.py
> +# default is STRING, only need to put the non-STRING keys in here
we could remove DTYPE_2_TABLETYPE above if it is now unused.

2021-05-25 11:53 UTC, thomasyu888 commented on synapseclient/table.py
> +from pandas.api.types import infer_dtype
Does this function read in the entire column of values to determine the type?

2021-08-19 14:03 UTC, thomasyu888 approved these changes

2021-08-19 14:03 UTC, merged